n=input('Digite algo:')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços? ', n.isspace())
print('é um numeros?', n.isalnum())
print('é alfabético?', n.isalpha())
print('é alfanumérico?', n.isalnum())
print('Está em maisculo?',n.isupper())
print(' Está em minusculo?', n.islower())