n = str(input('Digite o seu nome completo:'))
nome = n.split()
print('Muito prazer em te conhecer!')
print('O primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))
